// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVQH-UzTY9Ek7gj9PyT9VOYIba8sNcei4',
    appId: '1:70073608383:web:c60574b99deb9f3d58fe0a',
    messagingSenderId: '70073608383',
    projectId: 'chataap-eb454',
    authDomain: 'chataap-eb454.firebaseapp.com',
    storageBucket: 'chataap-eb454.appspot.com',
    measurementId: 'G-RQXYE54HF2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPe_t1v8yqwVFAE_JJLj__XE9zSWBZedU',
    appId: '1:70073608383:android:1beb82155c3ef97558fe0a',
    messagingSenderId: '70073608383',
    projectId: 'chataap-eb454',
    storageBucket: 'chataap-eb454.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIyCDdKtz4yTLvhF_L7wM-c2SDGJlFCvo',
    appId: '1:70073608383:ios:210e1c84e769e45d58fe0a',
    messagingSenderId: '70073608383',
    projectId: 'chataap-eb454',
    storageBucket: 'chataap-eb454.appspot.com',
    iosClientId: '70073608383-hc3t0f4if25e2ljsoavlu3rvqk4trpit.apps.googleusercontent.com',
    iosBundleId: 'chatApp.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIyCDdKtz4yTLvhF_L7wM-c2SDGJlFCvo',
    appId: '1:70073608383:ios:210e1c84e769e45d58fe0a',
    messagingSenderId: '70073608383',
    projectId: 'chataap-eb454',
    storageBucket: 'chataap-eb454.appspot.com',
    iosClientId: '70073608383-hc3t0f4if25e2ljsoavlu3rvqk4trpit.apps.googleusercontent.com',
    iosBundleId: 'chatApp.chatApp',
  );
}
